interface=wlan0
driver=nl80211
ssid=SERVER-IOT-XX
hw_mode=g
channel=11
country_code=AT
ieee80211d=1
wmm_enabled=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=__WPA_SERVER__
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
